### ISSUE TITLE
Release a new version on npm

### ISSUE THREAD

**Issue by aminya** [tree-sitter/node-tree-sitter#111]
Many merged pull requests are not released yet. It is not possible to use this package through GitHub due to submodules. So, publishing is the only solution. Could you please release a new version?

**Comment by rien** [comment]
There are some issues (#102 and #106 ) that are probably resolved by PR #95, these changes are on master but not released yet.

@maxbrunsfeld when could you find time to publish a new release of this package?

**Comment by MarkKahn** [comment]
bump

**Comment by tlm2021** [comment]
Also bumping this. Need to pick up some of the new fixes.
