### ISSUE TITLE
Module not found Error

### ISSUE THREAD

**Issue by hoangvu99** [tree-sitter/node-tree-sitter#122]
**I got these errors when i tried to install "tree-sitter" and "tree-sitter-python"**

WARNING in ./node_modules/tree-sitter-python/bindings/node/index.js 2:2-76
Module not found: Error: Can't resolve '../../build/Release/tree_sitter_python_binding' 

WARNING in ./node_modules/tree-sitter-python/bindings/node/index.js 8:4-76
Module not found: Error: Can't resolve '../../build/Debug/tree_sitter_python_binding' 

WARNING in ./node_modules/tree-sitter/index.js 3:12-66
Module not found: Error: Can't resolve './build/Release/tree_sitter_runtime_binding' 

WARNING in ./node_modules/tree-sitter/index.js 6:14-66
Module not found: Error: Can't resolve './build/Debug/tree_sitter_runtime_binding'

Help me!

**Comment by alehander92** [comment]
you need to use `npm i` in the `tree-sitter-python` folder: it seems to build the needed `_binding` files: at least this worked for a similar case for me
