### ISSUE TITLE
Error: compiled against a different Node.js version (108 vs 93)

### ISSUE THREAD

**Issue by jleven** [tree-sitter/node-tree-sitter#130]
Hi folks,

Love tree-sitter, just looking for some advice / being pointed in the right direction. Sorry if this is the wrong place to post this.

I have a node package that I run using npx in a github action. The whole thing runs great when I call it locally, but in a github action the node module versions don't match. I just call:

```
npx codesee <many> <more> <args>
```

(`codesee` depends on `node-tree-sitter`) and in the github action I get this error:

```
  Error: The module '/home/runner/.npm/_npx/4c2a8b93a2923ffe/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 108. This version of Node.js requires
  NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or `npm install`).
```

I'm happy to use an older version of node-tree-sitter to make this work, but how can I figure out which version of node-tree-sitter (if any) is compiled against `NODE_MODULE_VERSION 93`?

Or is there something weird in my github action environment? I would have thought `npx` would result in `node-tree-sitter` being compiled against the local version of node -- but I'm pretty new to working with node bindings, so to be honest I don't fully understand what's going on here.

**Comment by verhovsky** [comment]
I ran into this error today

```
Error: The module '/Users/space/code/third-party/node-tree-sitter/node_modules/tree-sitter-javascript/build/Release/tree_sitter_javascript_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

and this fixed it for me:

```sh
rm -rf node_modules
npm install
```

**Comment by segevfiner** [comment]
node-tree-sitter is now Node-API so this kind of errors shouldn't happen anymore. Although the cause of them is simply mixing Node and npm versions. e.g. `npm` is from one Node major version while you then try to run using a differnet Node major version.
