### ISSUE TITLE
ReferenceError: grammar is not defined

### ISSUE THREAD

**Issue by Mohan-Dhawan** [tree-sitter/node-tree-sitter#136]
I get this error when including my custom tree-sitter grammar in a Node JS program for parsing.
```
<path to parser>/grammar.js:10
module.exports = grammar({
^

ReferenceError: grammar is not defined
```
`tree-sitter parse <file>` works just fine and prints the AST on stdout, but including the parser in a JS code (as shown below) generates the error mentioned above
```
const Parser = require('tree-sitter');
const myGrammar = require('./grammar');
const parser = new Parser();
parser.setLanguage(myGrammar);
```
Is there something that I am missing?

**Comment by ChrisCookOC** [comment]
I ran into this and resolved it by changing the package.json on my grammar

Originally I had   "main": "grammar.js", and changing it to   "main": "bindings/node", resolved the issue
