### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by Sanger2000** [tree-sitter/node-tree-sitter#137]
When running tree-sitter in node.js, I get a segfault of the form:
```
62701 Segmentation fault: 11
```
I am using vitest. When I enable multiple threads to run the tests (which is enabled by default), I get the error above.

But it works perfectly fine when forcing vitest to run on a single thread. I believe vitest uses tinypool for multi-thread test running - https://github.com/tinylibs/tinypool.

Any ideas on why I might be encountering an error like this?

**Comment by verhovsky** [comment]
Could you create a reproducible test case please?

**Comment by verhovsky** [comment]
Possible related to #157
