### ISSUE TITLE
Module not found Error

### ISSUE THREAD

**Issue by goneXII** [tree-sitter/node-tree-sitter#153]
I got these errors when i tried to install "tree-sitter" and "tree-sitter-javascript"

`Module not found: Error: Can't resolve '../../build/Debug/tree_sitter_javascript_binding'

 warning  in ./node_modules/tree-sitter-javascript/bindings/node/index.js

Module not found: Error: Can't resolve '../../build/Release/tree_sitter_javascript_binding'

 warning  in ./node_modules/tree-sitter/index.js

Module not found: Error: Can't resolve './build/Debug/tree_sitter_runtime_binding' 

 warning  in ./node_modules/tree-sitter/index.js`

**Comment by verhovsky** [comment]
Duplicate of #122
