### ISSUE TITLE
Interest in prebuilt binaries?

### ISSUE THREAD

**Issue by wingrunr21** [tree-sitter/node-tree-sitter#16]
Hi,

Any interest in using something like [prebuild](https://github.com/prebuild/prebuild) to build/store prebuilt binaries for the major node/electron versions? Not sure how you're solving this problem for Atom but I'm trying to work through how to ship cross platform binaries for VSCode.

I've been messing around with how to get things to cooperate with Travis/Appveyor on [this branch](https://github.com/wingrunr21/node-tree-sitter/tree/add_prebuild_support) in my fork.

**Comment by maxbrunsfeld** [comment]
Yeah, I'd be open to using `prebuild`. If you open a PR that sets things up, I could add to our CI configurations any secure environment variables that are necessary to get it working.
