### ISSUE TITLE
Prebuild binaries for electron

### ISSUE THREAD

**Issue by sbasher314** [tree-sitter/node-tree-sitter#165]
Hello,

My team is recently unable to package our electron app, due to a deep dependency on version [v0.20.1](https://github.com/tree-sitter/node-tree-sitter/releases/tag/v0.20.1)

It appears that assets are available for v0.20.0 and v0.20.5.

Would it be possible to publish / republish the binaries for 0.20.1? We are working on updating our dependencies to hopefully avoid this issue on our end, with not much success.

**Comment by verhovsky** [comment]
I only have a mac, so I can't prebuild Windows binaries, sorry. The assets for [v0.20.0](https://github.com/tree-sitter/node-tree-sitter/releases/tag/v0.20.0) are only for some version 5 of Electron so they probably won't help you, you'll still end up needing a C++ compiler.

Also, v0.20.5 probably doesn't work with Electron 13+ on Windows, see https://github.com/tree-sitter/node-tree-sitter/pull/151#issuecomment-1611097026 If/when you upgrade, please let me know how it goes.

P.S. you can try adding this to your package.json to override node-tree-sitter but it's better to upgrade the dependency of course:

```json
  "devDependencies": {
    "node-tree-sitter": "^0.20.5",
    ...
  },
  "overrides": {
    "<name of package that depends on node-tree-sitter": {
      "node-tree-sitter": "$node-tree-sitter"
    }
  },
```

**Comment by segevfiner** [comment]
node-tree-sitter is now Node-API and should be compatible with Electron natively. This can be closed.
