### ISSUE TITLE
Silently fails while importing on VSCode extension debugger 

### ISSUE THREAD

**Issue by Yanqiao4396** [tree-sitter/node-tree-sitter#168]
OS version:13.2.1 
Node-tree-sitter version: 0.20.5
VSCode version: 1.83.0

I am planning to build a vscode extension with tree-sitter as I am impressed by tree-sitter's power on general parsing. However, I ran into a problem of importing tree-sitter with vscode development debugger. Every time break point comes to line `const TreeSitter =  require('tree-sitter');`, it broke silently. Not sure if it's because of VSCode or tree-sitter. Please help, it's getting frustrating.

```

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    let currentFileCheck = vscode.commands.registerCommand('currentWindow',()=>
    {
      const currentFile = vscode.window.activeTextEditor?.document;
      if ( typeof currentFile !== "undefined"){
        
        vscode.window.showInformationMessage(currentFile.fileName);
        vscode.window.showInformationMessage(currentFile.languageId);
        var fileText = currentFile.getText();
        const JavaScript =  require('tree-sitter-javascript');
        const TreeSitter =  require('tree-sitter');
        const parser = new TreeSitter();
        parser.setLanguage(JavaScript);
        // return 'hello-world'
        const tree = parser.parse(fileText);
        console.log(tree.rootNode)
      }
    });
    context.subscriptions.push(currentFileCheck);
    
}
```

**Comment by verhovsky** [comment]
Try building the latest version of node-tree-sitter from source. A VS Code crashing issue was fixed on master but hasn't been released yet (#109).

**Comment by Yanqiao4396** [comment]
@verhovsky , thank you for your response. After I `npm install` the main repo, should I build the library as mentioned in the [tree-sitter documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#building-the-library)?

**Comment by Yanqiao4396** [comment]
@verhovsky Thank you for your response. After `npm install` the main branch, I got the _class_ error:
```
The module '/Users/yanqiaochen/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 116. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
I've tried `rm -rf node_modules`, and then `npm install`, `./node_modules/.bin/electron-rebuild` as shown in https://github.com/electron/electron/blob/main/docs/tutorial/using-native-node-modules.md . Unfortunately, it doesn't work for me

**Comment by verhovsky** [comment]
I think what you need to do is `npm install tree-sitter` then

```
cd node_modules/tree-sitter
npx node-gyp rebuild
```

**Comment by Yanqiao4396** [comment]
Sorry for the misleading message above. I accidentally ran the debugger without installing the `tree-sitter` git repository in advance. After running `npm install git+ssh://git@github.com:tree-sitter/node-tree-sitter.git` now, I got a long error message ```
npm ERR! code 1
npm ERR! path /Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/tree-sitter
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@16.20.2 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/Users/yanqiaochen/.pyenv/versions/3.10.6/bin/python3"
npm ERR! gyp info spawn /Users/yanqiaochen/.pyenv/versions/3.10.6/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/tree-sitter/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/yanqiaochen/Library/Caches/node-gyp/16.20.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/yanqiaochen/Library/Caches/node-gyp/16.20.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/yanqiaochen/Library/Caches/node-gyp/16.20.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/tree-sitter',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: *** No rule to make target `Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o', needed by `Release/tree_sitter.a'.  Stop.
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.3.0
npm ERR! gyp ERR! command "/Users/yanqiaochen/.nvm/versions/node/v16.20.2/bin/node" "/Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/yanqiaochen/cs/comp/YanqiaoChen/map/node_modules/tree-sitter
npm ERR! gyp ERR! node -v v16.20.2
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yanqiaochen/.npm/_logs/2023-10-12T20_50_06_030Z-debug-0.log
```

**Comment by Yanqiao4396** [comment]
After failing to install `node-tree-sitter` with `npm`, I found it was possible to install with git and then compile with `npm run build`. However, after I added the local `tree-sitter` dependency with `npm install --save ../node-tree-sitter` and recompiled the `node-tree-sitter` with command `HOME=~/.electron-gyp node-gyp rebuild --target=1.2.3 --arch=x64 --dist-url=https://electronjs.org/headers`, I got error msg 

```
../src/util.cc:8:28: error: no member named 'InstanceOf' in 'v8::Value'
  auto maybe_bool = value->InstanceOf(Nan::GetCurrentContext(), object);
                    ~~~~~~~^
1 error generated.
make: *** [Release/obj.target/tree_sitter_runtime_binding/src/util.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/yanqiaochen/.nvm/versions/node/v16.20.2/lib/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Users/yanqiaochen/.nvm/versions/node/v16.20.2/bin/node" "/Users/yanqiaochen/.nvm/versions/node/v16.20.2/bin/node-gyp" "rebuild" "--target=1.2.3" "--arch=x64" "--dist-url=https://electronjs.org/headers"
gyp ERR! cwd /Users/yanqiaochen/cs/comp/YanqiaoChen/node-tree-sitter
gyp ERR! node -v v16.20.2
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 

```

I don't know which part did I mess up. I guess the package compilation?

**Comment by Yanqiao4396** [comment]
I uploaded the failing code to an isolated [repository](https://github.com/Yanqiao4396/failing-vscode-tree-sitter) with a reproduction instruction. Please check it and share insight. Any help will be appreciated

**Comment by Yanqiao4396** [comment]
This [issue](https://github.com/tree-sitter/node-tree-sitter/issues/169) provides a workaround to make `node-tree-sitter` work on vscode extension

**Comment by sogaiu** [comment]
IIUC, using the `.wasm` route technically speaking makes use of [something other than `node-tree-sitter](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web).
