### ISSUE TITLE
Implicit use of wrong grammar when multiple grammar directories are present

### ISSUE THREAD

**Issue by postsolar** [tree-sitter/node-tree-sitter#171]
**My issue**
There is a weird behaviour I notice, where if I have multiple directories with potentially different versions of the same grammar, TS would use the wrong version.

**Example**
An example directory structure:
```
~
 |-- tree-sitter-lang_branch1
 |    |-- grammar.js
 |    |-- src/
 |    ...
 |-- tree-sitter-lang_branch2
 |    |-- grammar.js
 |    |-- src/
 |    ...
```

If `tree-sitter-lang_branch1` was created earlier, then when I'm in `tree-sitter-lang_branch2` and running commands like `tree-sitter test` or `tree-sitter parse`, the grammar from `tree-sitter-lang_branch1` will be used.

**What I tried**
- Giving the CLI options a deeper look. There doesn't seem to be a flag related to choosing the grammar to use.
- Wiping `~/.cache/tree-sitter`. No effect.

**Comment by amaanq** [comment]
In package.json remove the filetype key in the "tree-sitter" field in the first grammar, though you should just use branches to swap between versions and not separate dirs imo (unless they're not from the same repo, but idk why you'd have both)

**Comment by postsolar** [comment]
Thanks!
