### ISSUE TITLE
electron version 19.0.17 

### ISSUE THREAD

**Issue by 878487489** [tree-sitter/node-tree-sitter#172]
electron version 19.0.17 Which version of tree-sitter should be used

**Comment by amaanq** [comment]
question makes no sense, sorry

**Comment by verhovsky** [comment]
The latest one, v0.20.6. Can you describe what issues you're having?

**Comment by 878487489** [comment]
Host System: Linux (Ubuntu)
Devcontainer: Ubuntu with Node 18
Electron 22.0.0
package.json
`  "keywords": [ "Electron", "quick", "start", "tutorial", "demo" ], "author": "GitHub", "license": "CC0-1.0", "devDependencies": { "electron": "22.0.0" }, "dependencies": { "electron-rebuild": "^3.2.9", "tree-sitter": "^0.20.6" }`
An error occurred
![image](https://github.com/tree-sitter/node-tree-sitter/assets/48462510/389c4ff8-501f-4e33-8394-73ca2be90508)
