### ISSUE TITLE
Special characters in rule names cause Uncaught SyntaxError

### ISSUE THREAD

**Issue by rien** [tree-sitter/node-tree-sitter#173]
I've encountered this issue when trying to load the node bindings of the [`tree-sitter-r` parser with their 'next' branch](https://github.com/r-lib/tree-sitter-r/tree/next). This grammar contains a lot of special symbols and as the node bindings [`generate a new class for each rule with its name`](https://github.com/tree-sitter/node-tree-sitter/blob/2f07fbd7047e6373c551b30f99e0f7a7a2ec7ad3/index.js#L725), this causes an `Uncaught SyntaxError` when the class definition is `eval`ed.

Now I've tried to fix this by creating a PR (https://github.com/r-lib/tree-sitter-r/pull/64) renaming all rules with special characters, but this is not as desired since it renames most of the original grammar.

What do you recommend a a good solution here? Should rule names with special characters be disallowed in grammars? Or should the node bindings be able to cope with these special characters as token names?

**Comment by verhovsky** [comment]
of course the node binding should be able to cope with arbitrary text in token names, whatever is supported by the regular library.

**Comment by amaanq** [comment]
I partially disagree - rules shouldn't be named like that, it makes no sense and it would be correct to have the upper node contain the special character text. I would argue R's grammar is not exactly written in the "standard" tree-sitter way of writing grammars
