### ISSUE TITLE
Electron error

### ISSUE THREAD

**Issue by 878487489** [tree-sitter/node-tree-sitter#174]
- Host System: Linux (Ubuntu)
- Devcontainer: Ubuntu with Node 18
- Electron 22.0.0
package.json
`  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "22.0.0"
  },
  "dependencies": {
    "electron-rebuild": "^3.2.9",
    "tree-sitter": "^0.20.6"
  }`
An error occurred
![image](https://github.com/tree-sitter/node-tree-sitter/assets/48462510/10a03b5d-9e5e-4a5c-b920-900ee9252632)

**Comment by amaanq** [comment]
Don't make a new issue - just use the one you already created to continue the conversation.
