### ISSUE TITLE
Repository name change name to tree-sitter-node

### ISSUE THREAD

**Issue by Angelk90** [tree-sitter/node-tree-sitter#183]
Hi @verhovsky,  I looked at the project names, I saw that most repositories start with this nomenclature:

tree-sitter-, then followed by the name of the language used.

Only some, like in this case node, use a different project nomenclature.

It would be possible to change the name of the repository to maintain this equality.

This is the list of all the repositories that have different nomenclature:
1) node-tree-sitter
2) py-tree-sitter
3) csharp-tree-sitter
4) haskell-tree-sitter
5) ruby-tree-sitter.old
6) rust-tree-sitter
7) afl-tree-sitter

**Comment by amaanq** [comment]
bindings use this convention, grammars use the other

**Comment by verhovsky** [comment]
language bindings are called language-tree-sitter and the parser for that language is called tree-sitter-language.

tree-sitter is a C library. If I want to write a program that uses tree-sitter but you don't want to write that program in C, how do you use a C library from Python or Node or whatever? You need language bindings. The difference between py-tree-sitter and tree-sitter-python is that tree-sitter-python is for parsing Python programs, whereas py-tree-sitter are Python bindings for tree-sitter, it is used for parsing programs in any programming language from Python.
