### ISSUE TITLE
console.log(node) does not match documentation

### ISSUE THREAD

**Issue by MichaReiser** [tree-sitter/node-tree-sitter#21]
Hy

I have written my own grammer with tree-sitter, that was quite easy! However, the nodes of the JS binding do not behave as I expected and the documentation makes you believe.

The readme states, that the call expression has properties like type, etc. when logged to the console:

```javascript
const callExpression = tree.rootNode.child(1).firstChild;
console.log(callExpression);

// { type: 'call_expression',
//   startPosition: {row: 0, column: 16},
//   endPosition: {row: 0, column: 30},
//   startIndex: 0,
//   endIndex: 30 }
```

If I execute the same example the output of the log statement is more like this:

```
SyntaxNode {
  '0': 36735152,
  '1': 1,
  '2': 22,
  '3': 0,
  '4': 22,
  '5': 0,
  tree:
   Tree {
     input: [Function: input],
     getText: [Function: getTextFromString] } }
```

This makes it difficult to inspect the AST. Especially since the node debugger seems to crash when inspecting a node `Assertion failed: (!tree->cached_nodes_.count(key)), function CacheNode, file ../src/tree.cc, line 225.`

Is there any documentation describing which properties I might expect from my grammer?

Thanks,
Micha

**Comment by MichaReiser** [comment]
This would greatly improve the explorability!
It seems that only the VS Code debugger struggles with the lib. If I'm debugging with WebStorm everything seems to be fine. So don't bother about that one.

**Comment by maxbrunsfeld** [comment]
I added an `inspect` method to `SyntaxNode`. Calling this `console.log` from node.js should use this method. In Electron, `console.log` doesn't appear to call `inspect`, so you would have to call `inspect` manually there.

**Comment by MichaReiser** [comment]
It seems that custom inspect functions are deprecated 

```
(node:5141) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

I personally do not understand why these props are not enumerable in the first place. Can you explain me the structure of the object. Maybe we can then find a proper binding so that internals remain internals and the api is clearly visible on the object.

**Comment by maxbrunsfeld** [comment]
Ah, thanks for pointing out that the plain `inspect` method was deprecated. I've updated to use the new `util.inspect.custom` symbol method.

As far as the marshaling, it is already implemented mostly in C++. The code may look a bit complex because it's been optimized to avoid having to read or write object properties from C++, which is very slow. Instead, values are transferred back and forth between JavaScript and C++ mostly using typed arrays, which is very fast.
