### ISSUE TITLE
Consider adding an async version of `Parser.parse`

### ISSUE THREAD

**Issue by segevfiner** [tree-sitter/node-tree-sitter#211]
Since parsing large files can take a while, and JS is single threaded, it might be helpful to add an async version of parse that will do the actual parsing on a separate thread, or a libuv worker thread via `napi_async_work`/`Napi:: AsyncWorker`. Of course, this is a trade off, as this will have more overhead due to needing to copy the input source string, as I don't think there is a safe way to lock it into place for access from other threads, but will allow freeing the event loop for other work.

**Comment by amaanq** [comment]
You can just set a timeout with `setTimeoutMicros` and keep reusing the same tree with a specified timeout to simulate "async" parsing. It'd be kind of hard to know when the parser is actually done with this method though, but you could probably check if `getChangedRanges` is empty to know it's done. I feel like using an `AsyncWorker` is an insane amount of overhead, whereas `setTimeoutMicros` is pretty lightweight

**Comment by segevfiner** [comment]
So maybe we want to add such a pseudo async version that handles that for the user? Although an `AsyncWorker` version will also be able to use multiple cores, though yeah, it has a large overhead...

**Comment by amaanq** [comment]
I really don't think an async version is needed - there's no other language binding that does this because you can effectively accomplish this by setting a timeout and implement that "pseudo-async" logic to fit your application's needs imo...
