### ISSUE TITLE
[question] How to query out the classes and funcs from source code? 

### ISSUE THREAD

**Issue by liaodalin19903** [tree-sitter/node-tree-sitter#213]
Hi, 

I know GitHub uses tree-sitter to query out the classes and funcs : 

![image](https://github.com/user-attachments/assets/a4860538-83de-45d0-ba83-4ae0f0352324)

but in tree-sitter I don't find a way to do it, is there any API to implment it? 
is there any higher level wrapper lib?

**Comment by segevfiner** [comment]
You use `Parser.Query` passing it the language and tree-sitter query string and then use its methods to look at the results. Documentation is missing for this ATM, but you can check out https://github.com/tree-sitter/node-tree-sitter/blob/master/test/query_test.js.
