### ISSUE TITLE
[question] I searched all the source code of `tree-sitter`, there is no `IdentifierNode`, why there has log? 

### ISSUE THREAD

**Issue by liaodalin19903** [tree-sitter/node-tree-sitter#217]
Hi, when I execute the code:

```
const tree = parser.parse(`
class Person {}
 
const TestPerson = class {}

class Person2 {}
 
const TestPerson2 = class {}
  `);
const matches = query.matches(tree.rootNode);

matches.forEach(item => {
  console.log(item.captures[0])  // there console the results
})

```

the result:
```
{
  name: 'class-name',
  node: IdentifierNode {
    type: identifier,
    startPosition: {row: 2, column: 6},
    endPosition: {row: 2, column: 12},
    childCount: 0,
  }
}
{
  name: 'class-name',
  node: IdentifierNode {
    type: identifier,
    startPosition: {row: 8, column: 6},
    endPosition: {row: 8, column: 13},
    childCount: 0,
  }
}
```

I have 2 questions about this:

1、you see the `node: IdentifierNode{...}`, it presents node is a instance of class `IdentifierNode`.

but I searched all the source code of `tree-sitter`, there is no `IdentifierNode`. 

2、I can get the class name by `node.text`, but you see there is no `text` property on class `IdentifierNode`, why there can get it?

**Comment by segevfiner** [comment]
`IdentifierNode` is part of the grammar that you are using. You will find it's definition there as part of the grammar.

The `text` property is from the prototype of that object. You can see the TypeScript types for reference.

**Comment by liaodalin19903** [comment]
> `IdentifierNode` is part of the grammar that you are using. You will find it's definition there as part of the grammar.
> 
> The `text` property is from the prototype of that object. You can see the TypeScript types for reference.

@segevfiner 
I'm so sorry to bother you, but what did you say 
` ` ` 
The text property is from the prototype of that object. You can see the TypeScript types for reference. 
` ` ` 
Where else can I find a concrete implementation?

is it [tree-sitter.d.ts#L64](https://github.com/tree-sitter/node-tree-sitter/blob/master/tree-sitter.d.ts#L64)?

or defined in typescript?
![QQ20240815-015859](https://github.com/user-attachments/assets/546103e3-e72e-41ec-b835-9a7ac1f63ef5)

**Comment by segevfiner** [comment]
tree-sitter.d.ts is just type definitions, the implementation is in index.js and the src folder.

For `text`: https://github.com/tree-sitter/node-tree-sitter/blob/59469711cecb2f042f091207aeca4fbddc629c4f/index.js#L128
https://github.com/tree-sitter/node-tree-sitter/blob/59469711cecb2f042f091207aeca4fbddc629c4f/index.js#L372
https://github.com/tree-sitter/node-tree-sitter/blob/59469711cecb2f042f091207aeca4fbddc629c4f/index.js#L734
