### ISSUE TITLE
[question] Why use `new Query()` to create query instance, the TypeScript will get error?

### ISSUE THREAD

**Issue by liaodalin19903** [tree-sitter/node-tree-sitter#219]
When use `new Query()` to create query instance, the TypeScript will get error:

1)JavaScript test success:
https://github.com/liaodalin19903/Test-demos/tree/bug-003-nodetreesitter/nodejs-test-demos/nodejs-demo-02-nodetreesitter 

new Query() execute no problem:
```
const query = new Query(
  JavaScript,
  `
    (class_declaration name: (identifier) @class-name)
  `
);
```

2)TypeScript test fail:
https://github.com/liaodalin19903/Test-demos/tree/bug-003-nodetreesitter/nodejs-test-demos/nodejs-demo-03-nodetreesitter

new Query() execute error
```
const query = new Query(
  TypeScript,
  `
    (class_declaration name: (identifier) @class-name)
  `
);
```

Error:
```
/usr/local/bin/node ./nodejs-test-demos/nodejs-demo-03-nodetreesitter/test.js
Uncaught Error Error: Query error of type TSQueryErrorStructure at position 31
    at <anonymous> (/Users/user/Desktop/Test/Test-demos/nodejs-test-demos/nodejs-demo-03-nodetreesitter/test.js:9:15)
    at Module._compile (internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (internal/modules/cjs/loader:1427:10)
    at Module.load (internal/modules/cjs/loader:1206:32)
    at Module._load (internal/modules/cjs/loader:1022:12)
    at executeUserEntryPoint (internal/modules/run_main:135:12)
    at <anonymous> (internal/main/run_main_module:28:49)
test.js:9
Process exited with code 1
```

**Comment by amaanq** [comment]
it's `type_identifier` not `identifier`, just look at a parse tree to see what you should query for.

![image](https://github.com/user-attachments/assets/5c37f9e3-9c53-4cc7-91c6-dfc3e8984c7e)

**Comment by liaodalin19903** [comment]
> it's `type_identifier` not `identifier`, just look at a parse tree to see what you should query for.
> 
> ![image](https://private-user-images.githubusercontent.com/29718261/358859865-5c37f9e3-9c53-4cc7-91c6-dfc3e8984c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDc5MDYsIm5iZiI6MTcyMzk0NzYwNiwicGF0aCI6Ii8yOTcxODI2MS8zNTg4NTk4NjUtNWMzN2Y5ZTMtOWM1My00Y2M3LTkxYzYtZGZjM2U4OTg0YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDAyMjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzIxNDQxZjlhMDc5NWI0M2MyMTdlNGMxZmMyY2NkZjg5MDgyMGQ1NDJlNjJmMDExZmFlMTUzYzg0YjNiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3shk5HpZ4GKRLU331Z8S34dm4mkTvmrc_eAVkB4DPdw)

thanks for your reply, 
What tool did you use to print the contents of the snapshot? 
Is it tree-sitter-cli?

**Comment by amaanq** [comment]
1. Yes it's the cli but it's a fork with the `-oc` flag, I'll upstream that functionality soon enough.

2. it's aliased, and it's in the JavaScript grammar (which TypeScript extends). `node-tree-sitter` is just the nodejs bindings for tree-sitter.
