### ISSUE TITLE
prebuild: doesn't have arm-64 

### ISSUE THREAD

**Issue by shivamsouravjha** [tree-sitter/node-tree-sitter#225]
* Why doesn't the prebuild have arm64? I'm using this dependency in a VSCode extension and because of this I get error 

`failed: No native build was found for platform=linux arch=arm64 runtime=electron abi=108 uv=1 armv=8 libc=glibc node=18.18.2`

* Upon a look on node modules I saw this.
<img width="212" alt="image" src="https://github.com/user-attachments/assets/23088fe7-4087-4817-bf33-620bfae019b3">

**Comment by ObserverOfTime** [comment]
Not relevant to this particular repo.

**Comment by ObserverOfTime** [comment]
PR welcome.
https://github.com/tree-sitter/node-tree-sitter/blob/9ea6558f5e732abed81511c7966c88e8d6d06f24/.github/workflows/build.yml#L42-L43
