### ISSUE TITLE
No release in six months?

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/node-tree-sitter#227]
Not trying to be an annoying "wen release" guy, just wondering whether this was an unintentional oversight. The rust & python tree-sitter bindings have seen releases while this one has not. Feel free to close if this is intentional!

**Comment by ObserverOfTime** [comment]
I don't maintain the Node bindings.

**Comment by gpetrov** [comment]
@verhovsky can you update to the latest tree-sitter 0.24.2 ?

**Comment by amaanq** [comment]
0.22 is out
