### ISSUE TITLE
Bump to C++20 prevents usage on Ubuntu 20.04 with Node.js <= 20

### ISSUE THREAD

**Issue by segevfiner** [tree-sitter/node-tree-sitter#232]
Node.js <= 20 minimum OS is Ubuntu 20.04, but this package has moved to C++20 which is unsupported on Ubuntu 20.04, which leads to https://github.com/tree-sitter/workflows/issues/16

That is, the official workflows to build grammars fail on Ubuntu 20.04 due to this if node-tree-sitter is upgrade to 0.22.0.

**Comment by ObserverOfTime** [comment]
The bump came _after_ the breakage.

**Comment by segevfiner** [comment]
That's prebuildify defaulting to the latest Node.js version for building node-api packages, we will also need to add `--target` to its invocation with an older version like 20.18.0 that uses C++17. (And also tree-sitter itself not requiring C++20 for this to work).

**Comment by amaanq** [comment]
Yeah good call on `--target`, I had no clue that was a thing. I've specified the target to be 20.9.0, and downgraded the C++ version to 17.
