### ISSUE TITLE
Add support for ts_tree_cursor_current_node

### ISSUE THREAD

**Issue by wingrunr21** [tree-sitter/node-tree-sitter#31]
Hey,

What are your thoughts on exposing `ts_tree_cursor_current_node` as a getter on `TreeCursor`?

**Comment by maxbrunsfeld** [comment]
Yes, this would definitely make sense; I just hadn't needed it so far.

**Comment by wingrunr21** [comment]
Ok cool. We'd also have the ability to remove the 6 accessor methods (start/end position, start/end index, type, name) since the current node can be returned as a `SyntaxNode` which already has those methods. The `TreeCursor` prototype could just proxy to those.

**Comment by maxbrunsfeld** [comment]
I think for performance I want to keep using those methods directly, since they are called a lot in atoms syntax highlighting code path.
