### ISSUE TITLE
N-API version of bindings

### ISSUE THREAD

**Issue by drom** [tree-sitter/node-tree-sitter#34]
N-API is a new, more portable way of creating Nodejs bindings : https://nodejs.org/api/n-api.html
Does it make sense porting `node-tree-sitter` from NAN to NAPI ?

**Comment by drom** [comment]
The main benefit of NAPI is no need for parser recompilation when running on node 6, 8, 10, 11+

**Comment by qarlosalberto** [comment]
I have the same problems in Visual Studio Code. It's really tedious use it in vscode :(

**Comment by MichaelBelousov** [comment]
there is apparently a [napi branch](https://github.com/tree-sitter/node-tree-sitter/tree/napi) in this repo which I was able to build but I am using the query API which seems to have been added after. I will reply again if I add NAPI bindings for the query API

**Comment by MichaelBelousov** [comment]
can confirm my fork works for my query API usage, and I've made a format for NAPI-compiled languages to be unwrapped and tested with a tiny alternate NAPI-bindings for tree-sitter-sql.

This works very well for me when developing a visual studio code extension. I use [prebuildify](https://github.com/prebuild/prebuildify) to build against electron and (I haven't tried cross-compiling yet) for multiple platforms. If someone else needs this, I can put the work into a pull request targeting the napi branch in this repository. My fork merged the tip of master as well so it is a more up-to-date version of the napi branch here.
