### ISSUE TITLE
node-gyp error while installing as dependency of tree-sitter-syntax

### ISSUE THREAD

**Issue by p-e-w** [tree-sitter/node-tree-sitter#4]
Atom 1.14.2 on Linux (Fedora 24)

When running the "Update Package Dependencies" command from the `tree-sitter-syntax` package I get an error message. On the same machine, `npm install tree-sitter` works without errors.

Relevant part of `npm-debug.log`:

```
665 silly lifecycle tree-sitter@0.4.6~install: Args: [ '-c', 'node-gyp rebuild' ]
666 silly lifecycle tree-sitter@0.4.6~install: Returned: code: 1  signal: null
667 info lifecycle tree-sitter@0.4.6~install: Failed to exec install script
668 verbose unlock done using [FILE]
669 silly rollbackFailedOptional Starting
670 silly rollbackFailedOptional Finishing
671 silly runTopLevelLifecycles Starting
672 silly runTopLevelLifecycles Finishing
673 silly install printInstalled
674 verbose stack Error: tree-sitter@0.4.6 install: `node-gyp rebuild`
674 verbose stack Exit status 1
674 verbose stack     at EventEmitter.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/lib/utils/lifecycle.js:242:16)
674 verbose stack     at emitTwo (events.js:87:13)
674 verbose stack     at EventEmitter.emit (events.js:172:7)
674 verbose stack     at ChildProcess.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/lib/utils/spawn.js:40:14)
674 verbose stack     at emitTwo (events.js:87:13)
674 verbose stack     at ChildProcess.emit (events.js:172:7)
674 verbose stack     at maybeClose (internal/child_process.js:827:16)
674 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
675 verbose pkgid tree-sitter@0.4.6
676 verbose cwd [DIRECTORY]
677 error Linux 4.9.13-101.fc24.x86_64
678 error argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "[HOME]/.atom/.apm/.apmrc" "--userconfig" "[HOME]/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.13" "--arch=x64"
679 error node v4.4.5
680 error npm  v3.10.5
681 error code ELIFECYCLE
682 error tree-sitter@0.4.6 install: `node-gyp rebuild`
682 error Exit status 1
683 error Failed at the tree-sitter@0.4.6 install script 'node-gyp rebuild'.
683 error Make sure you have the latest version of node.js and npm installed.
683 error If you do, this is most likely a problem with the tree-sitter package,
683 error not with npm itself.
683 error Tell the author that this fails on your system:
683 error     node-gyp rebuild
683 error You can get information on how to open an issue for this project with:
683 error     npm bugs tree-sitter
683 error Or if that isn't available, you can get their info via:
683 error     npm owner ls tree-sitter
683 error There is likely additional logging output above.
684 verbose exit [ 1, true ]
```

**Comment by maxbrunsfeld** [comment]
I can't see the compiler error. Is there more content in `npm-debug.log`?

**Comment by p-e-w** [comment]
Nope. I've updated the excerpt to contain everything after the `node-gyp rebuild` invocation. There is no compiler error anywhere in the file, and no other errors either except those shown above.

**Comment by maxbrunsfeld** [comment]
It looks like it failed to run the `node-gyp` utility on your system. There's not much information to go on. What led you to run the `Update Package Dependencies` command? What happens if you run `apm install` from the `tree-sitter-syntax` directory at the command line?

**Comment by p-e-w** [comment]
Didn't know about this usage of `apm` (though I'm still not sure what exactly it is intended to do, as it did *not* install the package – I still had to symlink the directory manually into `~/.atom/packages`).

Running `apm install` in the directory created the same `npm-debug.log` as the "Update Package Dependencies" command, but it also printed a bunch of additional stuff to the console...

... and buried in there, between stacktraces and deprecation warnings, I spotted this gem:

```
make: g++: Command not found
```

I feel like a fool now for not checking this first. At the same time, it's pretty sad that in 2017 build tools are still not smart enough to just scream "compiler missing!" when appropriate. It's literally impossible to deduce this from `npm-debug.log` alone.

Case closed.
