### ISSUE TITLE
Can we get a new 0.15 release?

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/node-tree-sitter#40]
Hey there,

I'm getting  a `RangeError: Incompatible language version. Expected 9. Got 10` error at the moment, and I think it's due to this not being updated to 0.15.x yet, as I build my language implementation with that.

Only getting it on linux and not on windows (which is weird i guess, but might be due to differences in building)

**Comment by Razzeee** [comment]
Ok I checked again, I'm getting the same problem on windows

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/tree-sitter/node-tree-sitter/pull/39.
