### ISSUE TITLE
Typescript definitions not up to date

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/node-tree-sitter#42]
The type definitions seem to miss some functions. https://github.com/tree-sitter/node-tree-sitter/blob/master/tree-sitter.d.ts

https://github.com/tree-sitter/node-tree-sitter/blob/master/src/parser.h

For e.g. ParseTextBuffer is missing.

**Comment by maxbrunsfeld** [comment]
I think this is a duplicate of #32.
