### ISSUE TITLE
Support queries

### ISSUE THREAD

**Issue by sguillia** [tree-sitter/node-tree-sitter#56]
Hi!

The tree sitter API allows to search for pattern with queries. I am wondering if it would be feasible to have a binding for this, and how you would approach this if contributors would like to implement it :-)

https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries

**Comment by sogaiu** [comment]
Have been using web-tree-sitter, but started noticing that the related processes (node in one case, vscode in another) disappear / die.  As part of diagnosing the issue, started using the node bindings to compare and haven't yet encountered the same process issues.  (Hope to have more to say when details become clearer.)

At any rate, was using the query API via web-tree-sitter and at first glance, that doesn't seem to be here in the node bindings, so here's another vote of interest :)

**Comment by smackesey** [comment]
It appears that the new Query-related types weren't added to the `.d.ts` file. No biggie but should be incorporated eventually.
