### ISSUE TITLE
parseTextBufferSync crash when passing in an existing tree

### ISSUE THREAD

**Issue by dschwen** [tree-sitter/node-tree-sitter#60]
```
    tree = parser.parseTextBufferSync(editor.getBuffer().buffer)
    newtree = parser.parseTextBufferSync(editor.getBuffer().buffer, tree)
```

crashes atom (The editor has crashed). Stepping into the second `parseTextBufferSync` call I see the crash happening on [line 318 in `index.js`](https://github.com/tree-sitter/node-tree-sitter/blob/8a2987eaa115c867afd6b86920f02c6a4747516a/index.js#L318) right when the `call` is executed:

```
  const tree = parseTextBufferSync.call(this, snapshot, oldTree, includedRanges);
```

P.S.: sorry for the issue blasting. I'm super excited about tree-sitter and I would prefer using the atom slack, but my invite request has ben unanswered for a few weeks

**Comment by verhovsky** [comment]
Closing this as `parseTextBuffer` and `parseTextBufferSync` were removed in #141 because superstring has been sunset.
