### ISSUE TITLE
Add documentation for how to use Query API

### ISSUE THREAD

**Issue by kkoomen** [tree-sitter/node-tree-sitter#70]
Hi,

I've noticed that #62 did implement the Query API and I sort of did figure it out on my own by just backtracing the packages, the functions being exposed etc, but only because I couldn't find *any* documentation on how to use the Query API in JavaScript/TypeScript.

Please add the required documentation in the README about how to use this. I personally feel it should include examples of the following
- How to create a query
- How to capture a node with a query
  - After capturing a node, how do I get a node inside this result? Python example: if I capture a function/method it's `name`, `parameters` and `body` and my goal is to get the parameter data, how do I get each parameter? Should I just use `parameters: (parameters (identifier) (identifier)) @function.parameters` and then loop over the result and filter the child nodes via `result.node.children.filter((node) => node.type === 'identifier')`? Or can this capturing be handled with queries as well? I'd like to get more information about this, since I can't find anything about this. 
- How queries work

Thanks.

**Comment by FractalHQ** [comment]
Hey @kkoomen - I'm really struggling with this as well.  I'm was hoping comeone could perhaps share a brief example of how to  effectively isolate nodes by type and extract their contents using queries in TS/JS?

**Comment by weeman1337** [comment]
As long there is no real documentation yet, you could at least have a look into the tests: https://github.com/tree-sitter/node-tree-sitter/blob/master/test/query_test.js

**Comment by kkoomen** [comment]
@weeman1337 I think by now more people had no choice but to look through tests yet, but there are _so_ many questions and cases that are not covered in those tests. Is there any plan to write documentation? I'm still waiting for this and it seems the development on the tree-sitter modules are slow, including response time from maintainers. Can this be more active as well?

**Comment by amaanq** [comment]
There's some API docs up [here](https://tree-sitter.github.io/node-tree-sitter/classes/Parser.Query.html), not perfect, but it's better than nothing. Ideally, for anyone reading this, you should get a high level overview of how queries work [here](https://tree-sitter.github.io/tree-sitter/using-parsers/queries) first, then look at the Node API docs.
