### ISSUE TITLE
Emits NODE_MODULE_VERSION error

### ISSUE THREAD

**Issue by Lereena** [tree-sitter/node-tree-sitter#74]
Hello. I'm trying to use node-tree-sitter v0.17.0 in my project using node v14.15.1, npm v6.14.8. 
The package installs without any error, but when I run a project it crashes with the following error:
```sh
Error: The module '/home/lereena/pabcnet-server-ts/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
I tried to remove `node_modules` and reinstall all the packages, to run `npm rebuild tree-sitter`, to downgrade node, but it didn't help. 
Is this some package issue or maybe somebody has an idea how to fix this?

**Comment by maxbrunsfeld** [comment]
This is a general issue with native node modules, not something specific to tree-sitter. It's hard to know exactly what's going on in your system. To fix it, you'll need to ensure that the same version of `node` is getting used when you *install* the module as when you *run* the module. For example, do you have multiple `npm` or `node` versions installed, and have a mismatched pair of them on your `PATH`?
