### ISSUE TITLE
Get NODE_MODULE_VERSION error when importing and using tree-sitter-javascript

### ISSUE THREAD

**Issue by TsukimiRini** [tree-sitter/node-tree-sitter#87]
My nodeJS version is 14.17.0, using yarn v1.22.10 as the package manager. My OS is macOS Big Sur 11.2.3.

When I add tree-sitter and tree-sitter-javascript to my vscode extension development project, all appears to be well. But when I try some basic usage of tree-sitter, the error occurs:
```
Activating extension 'xxx' failed: The module '/path/to/project/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)..
```
All i have done is like:
```
import * as TreeSitter from 'tree-sitter'
const JavaScript = require('tree-sitter-javascript')
const treeSitter = new TreeSitter()
treeSitter.setLanguage(JavaScript)
```

**Comment by ahlinc** [comment]
It looks like you have the same problem #86, try to follow instructions from official Electron documentation: https://www.electronjs.org/docs/tutorial/using-native-node-modules

**Comment by segevfiner** [comment]
It should be easier to use now, as the module is Node-API based, this can likely be closed.
