### ISSUE TITLE
How to efficiently get node under cursor

### ISSUE THREAD

**Issue by FoamScience** [tree-sitter/node-tree-sitter#97]
Hello,

I'm trying to get a node which is responsible for a specific position in the document; and was wondering
if there is a canonical way to do it.

Currently, I'm searching (in a trivial way) for the node manually starting from root node and down:
```typescript
        let offset = document.offsetAt(position)
        const tree = this.treeParser.parse(content);

        // Start from here
        let root = tree.rootNode;
        let closestNode = root;
        let nodeNotFound = true;
        while (nodeNotFound) {
            for (let child of root.children) {
                if (
                    (Math.abs(offset - child.startIndex) <= Math.abs(offset - closestNode.startIndex))
                    && (offset >= child.startIndex)
                )
                {
                    closestNode = child;
                }
            }
            if (root == closestNode)
            {
                nodeNotFound = false;
            }
            root = closestNode;
        }
        return root;

```

While this probably is efficient enough for most cases. Does anyone see an improvement?

**Comment by razzeee** [comment]
I'm doing it like this https://github.com/elm-tooling/elm-language-server/blob/main/src/util/treeUtils.ts#L755

But I'm not convinced, if it's exactly, what your after.

**Comment by FoamScience** [comment]
Yep, That's similar, but not with named descendant; Thanks I didn't know such method exists
